"""empty message

Revision ID: 6a8175d49ddd
Revises: 66402a110ece
Create Date: 2024-01-11 04:32:29.101634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8175d49ddd'
down_revision = '66402a110ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_list',
    sa.Column('deckId', sa.Integer(), nullable=True),
    sa.Column('cardId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cardId'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deckId'], ['decks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_list')
    # ### end Alembic commands ###