"""empty message

Revision ID: 3fab7223410b
Revises: f22e9fbe8afa
Create Date: 2024-01-28 18:08:41.717756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fab7223410b'
down_revision = 'f22e9fbe8afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=400), nullable=True))

    # ### end Alembic commands ###