"""empty message

Revision ID: 61786426933d
Revises: c8163669c89d
Create Date: 2024-01-28 18:14:24.275991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61786426933d'
down_revision = 'c8163669c89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###