"""empty message

Revision ID: 744640c5e83e
Revises: 0aab3945a2b5
Create Date: 2024-01-28 18:12:16.964585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744640c5e83e'
down_revision = '0aab3945a2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###