"""empty message

Revision ID: 013309ca16b9
Revises: aa6ec57eefe4
Create Date: 2024-01-10 04:04:35.608410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013309ca16b9'
down_revision = 'aa6ec57eefe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###