"""empty message

Revision ID: 93413fbf0499
Revises: 6a8175d49ddd
Create Date: 2024-01-11 04:40:40.630487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93413fbf0499'
down_revision = '6a8175d49ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_list', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###