"""empty message

Revision ID: f22e9fbe8afa
Revises: f8be341c60c7
Create Date: 2024-01-28 18:04:51.916209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22e9fbe8afa'
down_revision = 'f8be341c60c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=400), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###