"""empty message

Revision ID: 0aab3945a2b5
Revises: edac1ccaca77
Create Date: 2024-01-28 18:11:16.138953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aab3945a2b5'
down_revision = 'edac1ccaca77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###