"""empty message

Revision ID: 63c954377e81
Revises: 753971d6c760
Create Date: 2024-02-02 16:18:13.002040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c954377e81'
down_revision = '753971d6c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('manaCost', sa.VARCHAR(length=255), nullable=False),
    sa.Column('manaValue', sa.INTEGER(), nullable=True),
    sa.Column('types', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cardText', sa.VARCHAR(length=255), nullable=True),
    sa.Column('flavorText', sa.VARCHAR(length=255), nullable=True),
    sa.Column('power', sa.INTEGER(), nullable=True),
    sa.Column('toughness', sa.INTEGER(), nullable=True),
    sa.Column('expansion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rarity', sa.VARCHAR(length=255), nullable=True),
    sa.Column('releaseSet', sa.VARCHAR(length=255), nullable=True),
    sa.Column('allSets', sa.VARCHAR(length=400), nullable=True),
    sa.Column('artist', sa.VARCHAR(length=255), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=255), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=False),
    sa.Column('activateOnPlay', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###